# Generated by Django 5.2.8 on 2025-11-28 12:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accommodations', '0002_change_icon_to_filefield'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField(verbose_name='تاریخ ورود')),
                ('check_out_date', models.DateField(verbose_name='تاریخ خروج')),
                ('number_of_guests', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='تعداد مهمان')),
                ('total_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='قیمت کل (تومان)')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('confirmed', 'تایید شده'), ('cancelled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='accommodations.accommodation', verbose_name='اقامتگاه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'رزرو',
                'verbose_name_plural': 'رزروها',
                'ordering': ['-created_at'],
            },
        ),
    ]
