# Generated by Django 5.2.8 on 2025-11-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_reservation_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره تماس'),
        ),
    ]
