# Generated by Django 5.2.8 on 2025-11-30 09:34

import django.db.models.deletion
import sso_integration.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InjastUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(db_index=True, help_text='National ID from Injast JWT (nid field)', max_length=20, unique=True, verbose_name='National ID')),
                ('injast_access_token', sso_integration.models.EncryptedTextField(blank=True, help_text='Encrypted Injast JWT access token', null=True, verbose_name='Injast Access Token')),
                ('token_expires_at', models.DateTimeField(blank=True, help_text='When the Injast access token expires', null=True, verbose_name='Token Expires At')),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Mobile Number')),
                ('mobile_country_code', models.CharField(blank=True, default='98', max_length=5, null=True, verbose_name='Mobile Country Code')),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='Last time user data was synced from Injast', null=True, verbose_name='Last Synced At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='injast_user', to=settings.AUTH_USER_MODEL, verbose_name='Django User')),
            ],
            options={
                'verbose_name': 'Injast User',
                'verbose_name_plural': 'Injast Users',
                'ordering': ['-created_at'],
            },
        ),
    ]
