# Generated by Django 5.2.8 on 2025-11-12 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('city', models.CharField(max_length=100, verbose_name='شهر')),
                ('province', models.CharField(max_length=100, verbose_name='استان')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('capacity', models.IntegerField(verbose_name='ظرفیت')),
                ('beds_description', models.CharField(max_length=200, verbose_name='توضیحات تخت\u200cها')),
                ('area', models.IntegerField(verbose_name='متراژ (متر)')),
                ('price_per_night', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='قیمت هر شب (تومان)')),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='امتیاز')),
                ('main_image', models.ImageField(upload_to='accommodations/', verbose_name='تصویر اصلی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'اقامتگاه',
                'verbose_name_plural': 'اقامتگاه\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام')),
                ('icon', models.CharField(blank=True, max_length=100, null=True, verbose_name='آیکون')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'امکانات',
                'verbose_name_plural': 'امکانات',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AccommodationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='accommodations/images/', verbose_name='تصویر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='accommodations.accommodation', verbose_name='اقامتگاه')),
            ],
            options={
                'verbose_name': 'تصویر اقامتگاه',
                'verbose_name_plural': 'تصاویر اقامتگاه',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='accommodation',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='accommodations', to='accommodations.amenity', verbose_name='امکانات'),
        ),
    ]
