# Generated by Django 5.2.8 on 2025-11-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='amenities/icons/', verbose_name='آیکون SVG'),
        ),
    ]
