# Generated by Django 5.2.8 on 2025-11-30 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0002_change_icon_to_filefield'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='قیمت (تومان)')),
                ('status', models.CharField(choices=[('available', 'موجود'), ('unavailable', 'غیرموجود'), ('full', 'پر'), ('under_maintenance', 'در حال تعمیر'), ('blocked', 'مسدود'), ('reserved', 'رزرو شده')], default='available', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='accommodations.accommodation', verbose_name='اقامتگاه')),
            ],
            options={
                'verbose_name': 'وضعیت روزانه اقامتگاه',
                'verbose_name_plural': 'وضعیت\u200cهای روزانه اقامتگاه',
                'ordering': ['date'],
                'indexes': [models.Index(fields=['accommodation', 'date'], name='accommodati_accommo_7f0d25_idx'), models.Index(fields=['date', 'status'], name='accommodati_date_c0e7e1_idx')],
                'unique_together': {('accommodation', 'date')},
            },
        ),
    ]
